services:
  nginx:
    image: jizuzquiza/process-paas-dmn-nginx:1.0.0
    deploy:
      resources:
        limits:
          cpus: '0.01'
          memory: 64M
        reservations:
          memory: 64M
    ports:
    - 4000:4000
  loan-prequalification-decisions:
    image: jizuzquiza/loan-prequalification-decisions:1.0.0-native
    #image: jizuzquiza/loan-prequalification-decisions:1.0.0
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 64M
        reservations:
          memory: 64M
    ports:
    - 9001:8080
  greeting-decisions:
    image: jizuzquiza/greeting-decisions:1.0.0-native
    #image: jizuzquiza/greeting-decisions:1.0.0
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
        reservations:
          memory: 128M
    ports:
      - 9000:8080